dist: bionic
language: php
node_js:
  - 7.2

services:
  - mysql
env:
  global:
    - SELENIUM_HOST=127.0.0.1
    - LAUNCH_URL=http://172.17.0.1:8000

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS casdb;'
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm --name selenium selenium/standalone-chrome-debug
#  - sudo apt-get update
#  - sudo apt-get install -y xvfb libappindicator1 fonts-liberation
#  - wget http://security.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-browser_79.0.3945.79-0ubuntu0.19.10.2_amd64.deb
#  - wget https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip
#  - wget https://bit.ly/2TlkRyu
#  - unzip chromedriver_linux64.zip
#  - sudo dpkg -i chromium-browser*.deb
#  - ls -la
#  - mv 2TlkRyu 2TlkRyu.jar
#  - java -jar 2TlkRyu.jar -port 4444

install:
  - npm install

before_script:
  - mysql --defaults-extra-file=./config.cnf casdb < database/casdb.sql
  # - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
  # - mysql -u root -e "GRANT ALL ON casdb.* TO 'root'@'localhost';"
  - php -S 172.17.0.1:8000 &
  - until curl -s 172.17.0.1:8000; do sleep 5; done
  #  - sudo apt-get install apache2
  #  - sudo a2enmod actions
  #  - sudo a2enmod rewrite
  #  - echo "export PATH=$TRAVIS_BUILD_DIR" | sudo tee -a /etc/apache2/envvars > /dev/null
  ##  - touch /etc/apache2/conf.d/phpconfig
  #  - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/gistfile1.txt)" | sudo tee /etc/apache2/phpconfig > /dev/null
  #  - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/gistfile1.txt)" | sed -e "s,PATH,`pwd`/web,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  #  - sudo service apache2 restart

  #- mysql -u root -e "CREATE USER 'myproject'@'localhost' IDENTIFIED BY 'mypass'"
  #- mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'myproject'@'localhost' WITH GRANT OPTION;"
  #- bin/vendors install
#  - app/console doctrine:database:create
#  - app/console doctrine:schema:update --force
#  - app/console doctrine:fixtures:lono

script:
  - cd $TRAVIS_BUILD_DIR/
  - npm run test-e2e test/acceptance/features

cache:
  npm: true
